hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1200000
server:
  port: ${server_port:9097}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: do-payment-service
  devtools:
    remote:
      secret: mysecret

management:
  security:
    enabled: false

ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true